services:

  laravel-docker:
    container_name: imagesim
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
    ports:
      - 3306:3306
